In [2]:
import numpy as np


## Simultaneous linear equations

The purpose of linear algebra is to allow us to solive sets of simultaneous linear equations.  E.g.
$$
x + 2y +z = 8
$$
$$
2x + 3y - 2z = 2
$$
$$
x - 2y + 3z = 6
$$
This can be easily represented using matrices and vectors to the equation $ Ax = b $

We can use NumPy to define the matrices for $A$ and $b$.  These will also give us access to the methods an properties to solve for **x**$ = (x, y, x)$

In [5]:
A = np.matrix('1 2 1; 2 3 -2; 1 -2 3')  # A maxtric of coefficients - defined as a string kind of following MATLAB syntax
print(A)

b = np.matrix('8;2;6') # A columnar vector of our right hand side values
print(b)


[[ 1  2  1]
 [ 2  3 -2]
 [ 1 -2  3]]
[[8]
 [2]
 [6]]


## Solution
This bit is still pretty easy.  Since our relationship is defined as $Ax=b$ we just divide both sides by $A$.  This is the same as multiplying by the inverse which is how we will proceed here.  Thankfully NumPy makes accessing the inverse of a matric pretty easy.  Let's solve our equations for $ x, y, and z$

In [6]:
x = A.I*b  # .I attribute is the inversion of the matrix A
print(x)

[[1.]
 [2.]
 [3.]]


## Imperfect Matrices
The above solution was so easy partially because our matrix and the equations that built it were well formed (i.e. independant equations and 1 equation for each variable).  Let's take a look at a situation where these conditions are not quite met.

### Equations
$$
x + 2y + z = 8
$$
$$
2x + 3y - 2z = 2
$$
$$
3x + 5y -z = 10
$$
The issue we have here is that equation 3 is basically just the first two added together and therefore it is not linearly independent.  This means we functionally only have 2 equations for 3 unkowns.  We kind of know this won't work as we expect but let's give it a shot anyway

In [12]:
A = np.matrix([[1,2,1],[2,3,-2], [3, 5, -1]]) # Defining our coefficient matrix using a more Python native syntax (lists of lists)
print(A)
b = np.matrix([[8], [2], [10]])
print(b)
print(np.linalg.matrix_rank(A) )# Less than 3 means this matrix is rank deficient - this means we cannot proceed without some more mathematical trickery.
print(np.linalg.det(A))  # The determinant is basically 0 and this means our matrix is singular.

[[ 1  2  1]
 [ 2  3 -2]
 [ 3  5 -1]]
[[ 8]
 [ 2]
 [10]]
2
-1.2582527612418447e-15


## SVD - Decomposing our Matrix
Without going through all the tedious derivation (because I don't want to look it all up) we can just assert that any matrix can be defined as composed of three components $A = USV$
We are particularly interested in the S component which is a diagonal matrix of $MxM$ dimensions whose diagonal values are called _singular values_.  If our matrix is rank deficient then one or more may be zero.  This can lead to a tedious divide by zero error when attempting to invert the matrix.  Let's take a look at how we could correct that.

Since s is a diagonal matrix where the only values of importance are on the diagonal, NumPy returns this as a vector.

In [13]:
u, s, vh = np.linalg.svd(A)
print(s)  # THe problem is that third one, which is close enough to zero to cause us problems

[7.37275014e+00 1.90854796e+00 3.51985320e-16]


In [15]:
# We set our troublesome element equal to 1
s[2] = 1
print(s)

[7.37275014 1.90854796 1.        ]


In [30]:
# We invert this vector and then set the last element to 0 (insted of infinity)
w = 1/s
w[2] = 0
BGI = vh * np.diag(w) * u.I #  A sneaky way to get our inverted A matrix

In [31]:
BGI*A

matrix([[ 0.25356619,  0.21431192, -0.91771568],
        [-0.00122957,  0.05871447,  0.24346485],
        [-0.43963443, -0.84154547, -0.28874086]])

In [32]:
BGI*b

matrix([[-2.07095701],
        [ 0.8465939 ],
        [-2.98894794]])

## Final Thoughts
I think there are likely some differences between the operations being called in NumPy vs MATLAB.  These values are not what I expected.  However, rather than spend too much time diving into why right now I'm going to push on and just be aware of the discrepancies.  I really just want to get to the fun stuff like analyzing sunspot activity or building multi-box models describing ion concentrations in the world ocean basins.